const challenges = {
    1: {"challenge": "Alongamento de braços acima da cabeça", "points": 10},
    2: {"challenge": "Rotação de ombros para frente e para trás", "points": 15},
    3: {"challenge": "Alongamento de pescoço", "points": 8},
    4: {"challenge": "Alongamento de pernas (toque os dedos dos pés)", "points": 12},
    5: {"challenge": "Alongamento de quadríceps (puxe o calcanhar em direção ao glúteo)", "points": 18},
    6: {"challenge": "Rotação de tornozelo", "points": 6},
    7: {"challenge": "Alongamento de panturrilhas", "points": 10},
    8: {"challenge": "Polichinelos", "points": 20},
    9: {"challenge": "Corrida no lugar com elevação de joelhos", "points": 25},
    10: {"challenge": "Pular corda", "points": 30},
    11: {"challenge": "Agachamentos", "points": 15},
    12: {"challenge": "Afundos (lunges)", "points": 18},
    13: {"challenge": "Flexões de braço (push-ups)", "points": 20},
    14: {"challenge": "Prancha", "points": 22},
    15: {"challenge": "Abdominais (crunches)", "points": 15},
    16: {"challenge": "Elevação de pernas", "points": 12},
    17: {"challenge": "Elevação de braços laterais", "points": 10},
    18: {"challenge": "Flexão de punhos", "points": 8},
    19: {"challenge": "Rotação de tronco", "points": 10},
    20: {"challenge": "Alongamento de glúteos", "points": 12},
    21: {"challenge": "Agachamento com salto", "points": 20},
    22: {"challenge": "Toques nos calcanhares com os dedos", "points": 8},
    23: {"challenge": "Flexão de joelhos com salto", "points": 18},
    24: {"challenge": "Dança ou movimentos de dança", "points": 25},
    25: {"challenge": "Movimentos de boxe no ar", "points": 20},
    26: {"challenge": "Alongamento de panturrilha na parede", "points": 10},
    27: {"challenge": "Alongamento de flexores do quadril", "points": 12},
    28: {"challenge": "Circundução de braços", "points": 8},
    29: {"challenge": "Elevação de calcanhares", "points": 6},
    30: {"challenge": "Alongamento de isquiotibiais", "points": 12},
    31: {"challenge": "Rotação de punhos", "points": 6},
    32: {"challenge": "Alongamento de ombros cruzados", "points": 10},
    33: {"challenge": "Alongamento de tornozelo com apoio", "points": 8},
    34: {"challenge": "Agachamento sumô", "points": 15},
    35: {"challenge": "Flexão de punhos com rotação", "points": 12},
    36: {"challenge": "Flexão de cotovelos com joelhos elevados", "points": 10},
    37: {"challenge": "Toque de calcanhar com rotação de tronco", "points": 8},
    38: {"challenge": "Marcha estacionária com giros de quadril", "points": 6},
    39: {"challenge": "Alongamento de panturrilha em pé", "points": 8},
    40: {"challenge": "Elevação de pernas alternadas", "points": 10},
    41: {"challenge": "Corrida lateral", "points": 12},
    42: {"challenge": "Alongamento de adutores", "points": 6},
    43: {"challenge": "Alongamento de tríceps", "points": 8},
    44: {"challenge": "Flexão de punhos alternada", "points": 6},
    45: {"challenge": "Alongamento de isquiotibiais sentado", "points": 8},
    46: {"challenge": "Abdominais com rotação de tronco", "points": 15},
    47: {"challenge": "Elevação de joelhos cruzados", "points": 10},
    48: {"challenge": "Agachamento com chute frontal", "points": 12},
    49: {"challenge": "Movimentos de ioga (por exemplo, saudação ao sol)", "points": 20},
    50: {"challenge": "Alongamento de peitoral com apoio em parede", "points": 8}
  }
    
  
  
  export  default  challenges;